# Generated by Django 5.2.7 on 2025-11-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Paleteria', '0004_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.cliente')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
